---
abstract: 'A bcrypt-capable mkpasswd'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-bmkpasswd
provides:
  App::bmkpasswd:
    file: lib/App/bmkpasswd.pm
    version: 0.04
recommends:
  Crypt::Passwd::XS: 0
requires:
  Crypt::Eksblowfish: 0.003
  Getopt::Long: 0
  Term::ReadKey: 0
  Time::HiRes: 0
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
