---
abstract: 'bcrypt-capable mkpasswd(1) and exported helpers'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-bmkpasswd
provides:
  App::bmkpasswd:
    file: lib/App/bmkpasswd.pm
    version: 1.07
recommends:
  Crypt::Passwd::XS: 0
requires:
  Crypt::Eksblowfish: 0.003
  Getopt::Long: 2.24
  Term::ReadKey: 0
  Time::HiRes: 0
  Try::Tiny: 0
  perl: v5.8.0
  strictures: 1
resources:
  license: http://dev.perl.org/licenses/
version: 1.07
