---
abstract: 'bcrypt-capable mkpasswd(1) and exported helpers'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-bmkpasswd
recommends:
  Crypt::Passwd::XS: 0
  Math::Random::ISAAC::XS: 0
requires:
  Bytes::Random::Secure: 0.24
  Carp: 0
  Crypt::Eksblowfish: 0.003
  Exporter::Tiny: 0
  Getopt::Long: 2.24
  POSIX: 0
  Pod::Usage: 1.51
  Time::HiRes: 0
  Try::Tiny: 0.12
  strictures: 1
resources:
  repository: git://github.com/avenj/app-bmkpasswd.git
version: 2.003001
